name: Scrape OTA rates

on:
  schedule:
    - cron: "*/115 * * * *" # every 30 minutes
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright
        run: |
          npm init -y
          npm i playwright@1
          npx playwright install --with-deps chromium

      - name: Run scraper
        run: node scrape.js

      - name: Commit rates.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rates.json
          git commit -m "Update rates.json [skip ci]" || echo "No changes to commit"
          git push
